# Generated by Django 3.2.12 on 2023-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartex',
            name='userid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
