# Generated by Django 3.2.12 on 2023-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
