# Generated by Django 3.2.12 on 2023-04-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='cartitem',
        ),
    ]
