# Generated by Django 3.2.12 on 2023-04-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cartex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartex',
        ),
    ]
