# Generated by Django 3.2.12 on 2023-04-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
    ]
