# Generated by Django 3.2.12 on 2023-04-30 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('api', '0013_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('address', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
    ]
