# Generated by Django 3.2.12 on 2023-04-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profilemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilemodel',
        ),
    ]
