# Generated by Django 3.2.12 on 2023-04-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='addressid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
