# Generated by Django 3.2.12 on 2023-04-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_addressid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='addressid',
        ),
    ]
