# Generated by Django 3.2.12 on 2023-04-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
