# Generated by Django 3.2.12 on 2023-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signup_logged'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='superuser',
            field=models.BooleanField(default=False),
        ),
    ]
