# Generated by Django 3.2.12 on 2023-04-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_remove_address_addressid'),
        ('profileapp', '0002_remove_profilemodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
