# Generated by Django 3.2.12 on 2023-04-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_profilemodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='userid',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
